"""add document chunk embeddings

Revision ID: 0fba5609e180
Revises: 3a72ff1a1c70
Create Date: 2026-04-06 15:38:00.206793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0fba5609e180'
down_revision: Union[str, None] = '3a72ff1a1c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("'My Chatbot'"), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', name='chatbot_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('iframe_token', sa.String(length=64), nullable=False, comment='Public embed key. Never expose tenant_id in widget URL.'),
    sa.Column('identity', sa.Enum('website', 'veloce_demo', name='chatbot_identity'), server_default=sa.text("'website'"), nullable=False),
    sa.Column('system_prompt_template', sa.Text(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('rag_enabled', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='Flipped TRUE by worker after first DocumentChunk written. Never flip manually.'),
    sa.Column('auto_close_minutes', sa.Integer(), server_default=sa.text('15'), nullable=False),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('lead_capture_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iframe_token')
    )
    op.create_index('ix_chatbot_configs_iframe_token', 'chatbot_configs', ['iframe_token'], unique=False)
    op.create_index(op.f('ix_chatbot_configs_public_id'), 'chatbot_configs', ['public_id'], unique=True)
    op.create_index('ix_chatbot_configs_status', 'chatbot_configs', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_chatbot_configs_tenant', 'chatbot_configs', ['tenant_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('chatbot_config_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('website', 'pdf', 'text', name='source_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_config_id'], ['chatbot_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_sources_chatbot', 'knowledge_sources', ['chatbot_config_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_public_id'), 'knowledge_sources', ['public_id'], unique=True)
    op.create_index('ix_knowledge_sources_tenant', 'knowledge_sources', ['tenant_id'], unique=False)
    op.create_index('ix_knowledge_sources_type', 'knowledge_sources', ['tenant_id', 'type'], unique=False)
    op.create_table('widget_themes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('chatbot_config_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default=sa.text("'Default Theme'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='One TRUE per chatbot. Enforced by partial unique index. Swap in transaction.'),
    sa.Column('is_paid_theme', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('typography', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_config_id'], ['chatbot_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_widget_themes_chatbot', 'widget_themes', ['chatbot_config_id'], unique=False)
    op.create_index('ix_widget_themes_one_active', 'widget_themes', ['chatbot_config_id'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index(op.f('ix_widget_themes_public_id'), 'widget_themes', ['public_id'], unique=True)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('knowledge_source_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Denormalized for direct tenant-scoped queries.'),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='crawl_status'), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('pages_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pages_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pages_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.BigInteger(), nullable=True, comment='NULL = scheduled. Populated = manually triggered.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_public_id'), 'crawl_jobs', ['public_id'], unique=True)
    op.create_index('ix_crawl_jobs_queued', 'crawl_jobs', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_index('ix_crawl_jobs_source', 'crawl_jobs', ['knowledge_source_id'], unique=False)
    op.create_index('ix_crawl_jobs_tenant', 'crawl_jobs', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('knowledge_source_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Denormalized — avoids joining knowledge_sources for tenant-scoped queries.'),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment="'pdf' for now. 'docx', 'xlsx' in future."),
    sa.Column('file_size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True, comment='Raw bytes. NULL after migrating to S3. Can clear after chunking.'),
    sa.Column('storage_path', sa.String(length=1000), nullable=True, comment='S3/GCS object key. NULL while using file_data.'),
    sa.Column('status', sa.Enum('uploading', 'processing', 'ready', 'failed', name='doc_status'), server_default=sa.text("'uploading'"), nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True, comment='NULL for crawled pages. Populated for manual uploads.'),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_public_id'), 'documents', ['public_id'], unique=True)
    op.create_index('ix_documents_source', 'documents', ['knowledge_source_id'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False, postgresql_where=sa.text("status IN ('uploading', 'processing')"))
    op.create_index('ix_documents_tenant', 'documents', ['tenant_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Denormalized. Always include in RAG WHERE clause to prevent cross-tenant leakage.'),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True, comment='pgvector embedding. Tenant-scoped cosine search.'),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='{"page": 3, "source_url": "...", "token_count": 312}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_document_index')
    )
    op.create_index('ix_chunks_document', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_tenant', 'document_chunks', ['tenant_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'crawled', name='listing_source'), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='Dedup key for crawled listings. NULL for manual entries.'),
    sa.Column('crawl_job_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'sold', 'leased', name='listing_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('listing_type', sa.Enum('sale', 'rent', name='listing_type'), server_default=sa.text("'sale'"), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price_display', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'AUD'"), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('suburb', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=5), server_default=sa.text("'AU'"), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('garages', sa.Integer(), nullable=True),
    sa.Column('land_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('house_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('has_pool', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_bedrooms', 'listings', ['tenant_id', 'bedrooms', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_listings_deleted_at'), 'listings', ['deleted_at'], unique=False)
    op.create_index('ix_listings_external', 'listings', ['tenant_id', 'external_id'], unique=False, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_index('ix_listings_price', 'listings', ['tenant_id', 'price', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_listings_public_id'), 'listings', ['public_id'], unique=True)
    op.create_index('ix_listings_state', 'listings', ['tenant_id', 'state', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_listings_suburb', 'listings', ['tenant_id', 'suburb', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_listings_tenant', 'listings', ['tenant_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_listings_type', 'listings', ['tenant_id', 'listing_type', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_tenants_public_id', table_name='tenants')
    op.create_index('ix_tenants_public_id', 'tenants', ['public_id'], unique=False)
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    op.drop_index('ix_tenants_public_id', table_name='tenants')
    op.create_index('ix_tenants_public_id', 'tenants', ['public_id'], unique=True)
    op.drop_index('ix_listings_type', table_name='listings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_listings_tenant', table_name='listings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_listings_suburb', table_name='listings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_listings_state', table_name='listings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_listings_public_id'), table_name='listings')
    op.drop_index('ix_listings_price', table_name='listings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_listings_external', table_name='listings', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index(op.f('ix_listings_deleted_at'), table_name='listings')
    op.drop_index('ix_listings_bedrooms', table_name='listings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('listings')
    op.drop_index('ix_chunks_tenant', table_name='document_chunks')
    op.drop_index('ix_chunks_embedding', table_name='document_chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_documents_tenant', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents', postgresql_where=sa.text("status IN ('uploading', 'processing')"))
    op.drop_index('ix_documents_source', table_name='documents')
    op.drop_index(op.f('ix_documents_public_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_crawl_jobs_tenant', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_source', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_queued', table_name='crawl_jobs', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_crawl_jobs_public_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_widget_themes_public_id'), table_name='widget_themes')
    op.drop_index('ix_widget_themes_one_active', table_name='widget_themes', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index('ix_widget_themes_chatbot', table_name='widget_themes')
    op.drop_table('widget_themes')
    op.drop_index('ix_knowledge_sources_type', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_tenant', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_public_id'), table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_chatbot', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index('ix_chatbot_configs_tenant', table_name='chatbot_configs')
    op.drop_index('ix_chatbot_configs_status', table_name='chatbot_configs')
    op.drop_index(op.f('ix_chatbot_configs_public_id'), table_name='chatbot_configs')
    op.drop_index('ix_chatbot_configs_iframe_token', table_name='chatbot_configs')
    op.drop_table('chatbot_configs')
    # ### end Alembic commands ###