"""hnsw_tsvector_listing_embedding_chatbot_assets

Revision ID: 1f71dab81632
Revises: 274ffedff5cc
Create Date: 2026-04-09 23:04:22.754382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '1f71dab81632'
down_revision: Union[str, None] = '274ffedff5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('chatbot_config_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type e.g. image/png — returned as Content-Type when serving.'),
    sa.Column('file_size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False, comment='Raw image bytes. Clear after migrating to S3.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False, comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.'),
    sa.ForeignKeyConstraint(['chatbot_config_id'], ['chatbot_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatbot_assets_chatbot', 'chatbot_assets', ['chatbot_config_id'], unique=False)
    op.create_index(op.f('ix_chatbot_assets_public_id'), 'chatbot_assets', ['public_id'], unique=True)
    op.create_index('ix_chatbot_assets_tenant', 'chatbot_assets', ['tenant_id'], unique=False)
    op.add_column('document_chunks', sa.Column('ts_content', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(content, ''))", persisted=True), nullable=True, comment='GENERATED tsvector for FTS. Auto-computed from content by Postgres.'))
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(1536),
               comment='pgvector embedding. Tenant-scoped cosine search via HNSW index.',
               existing_comment='pgvector embedding. Tenant-scoped cosine search.',
               existing_nullable=True)
    # Drop old IVFFlat index if it exists (may not exist on fresh DBs)
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding")
    op.create_index('ix_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_ts_content', 'document_chunks', ['ts_content'], unique=False, postgresql_using='gin')
    op.add_column('listings', sa.Column('embedding', Vector(1536), nullable=True, comment='pgvector embedding for semantic listing search. HNSW-indexed.'))
    op.create_index('ix_listings_embedding_hnsw', 'listings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL AND embedding IS NOT NULL'))
    op.drop_index('ix_tenants_public_id', table_name='tenants')
    op.create_index('ix_tenants_public_id', 'tenants', ['public_id'], unique=False)
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    op.drop_index('ix_tenants_public_id', table_name='tenants')
    op.create_index('ix_tenants_public_id', 'tenants', ['public_id'], unique=True)
    op.drop_index('ix_listings_embedding_hnsw', table_name='listings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('deleted_at IS NULL AND embedding IS NOT NULL'))
    op.drop_column('listings', 'embedding')
    op.drop_index('ix_chunks_ts_content', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(1536),
               comment='pgvector embedding. Tenant-scoped cosine search.',
               existing_comment='pgvector embedding. Tenant-scoped cosine search via HNSW index.',
               existing_nullable=True)
    op.drop_column('document_chunks', 'ts_content')
    op.drop_index('ix_chatbot_assets_tenant', table_name='chatbot_assets')
    op.drop_index(op.f('ix_chatbot_assets_public_id'), table_name='chatbot_assets')
    op.drop_index('ix_chatbot_assets_chatbot', table_name='chatbot_assets')
    op.drop_table('chatbot_assets')
    # ### end Alembic commands ###
