"""update conversations and messages tables

Revision ID: 20b3651eeb1b
Revises: af76ac4b52ee
Create Date: 2026-02-18 11:49:06.262137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b3651eeb1b'
down_revision: Union[str, None] = 'af76ac4b52ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'Conversation_uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('messages', sa.Column('messages_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'messages_uuid')
    op.alter_column('conversations', 'Conversation_uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
