"""add_is_superadmin_to_users

Revision ID: 274ffedff5cc
Revises: <keep generated>
Create Date: 2026-04-09 18:32:38.138069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '274ffedff5cc'
down_revision: Union[str, None] = '<keep generated>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addons', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name e.g. Extra User Seat',
               existing_nullable=False)
    op.alter_column('addons', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-safe unique key e.g. extra-users',
               existing_nullable=False)
    op.alter_column('addons', 'type',
               existing_type=postgresql.ENUM('extra_users', 'extra_conversations', 'extra_storage', 'premium_widget', name='addon_type'),
               comment='Addon category — drives which limit key is incremented',
               existing_nullable=False)
    op.alter_column('addons', 'price_aud_cents',
               existing_type=sa.INTEGER(),
               comment='Per unit per billing interval in AUD cents',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('addons', 'price_usd_cents',
               existing_type=sa.INTEGER(),
               comment='Per unit per billing interval in USD cents',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('addons', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='e.g. { "grants_per_unit": { "max_users": 1 } }',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('addons', 'stripe_price_id',
               existing_type=sa.VARCHAR(length=255),
               comment='STRIPE_HOOK: Stripe price ID for this addon',
               existing_nullable=True)
    op.alter_column('addons', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('addons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('addons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('chatbot_configs', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('chatbot_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('chatbot_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('crawl_jobs', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('documents', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('knowledge_sources', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('listings', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('listings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = active record. Non-NULL = soft-deleted. Always set to UTC.',
               existing_nullable=True)
    op.alter_column('otp_verifications', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name e.g. Project Developments, Single Office Businesses',
               existing_nullable=False)
    op.alter_column('plans', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='URL-safe unique key e.g. project-developments-monthly',
               existing_nullable=False)
    op.alter_column('plans', 'price_aud_cents',
               existing_type=sa.INTEGER(),
               comment='AUD price in cents. e.g. 30000 = AUD 300.00',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('plans', 'price_usd_cents',
               existing_type=sa.INTEGER(),
               comment='USD price in cents. 0 = AUD only plan',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('plans', 'limits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Entitlement caps. Keys: max_users, max_chatbots, max_conversations_per_month, max_tokens_per_month, max_tokens_per_conversation, max_documents, max_pages_crawled, max_listings, max_storage_mb. Update via API — no migration needed.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plans', 'stripe_monthly_price_id',
               existing_type=sa.VARCHAR(length=255),
               comment='STRIPE_HOOK: Stripe price ID for monthly billing',
               existing_nullable=True)
    op.alter_column('plans', 'stripe_annual_price_id',
               existing_type=sa.VARCHAR(length=255),
               comment='STRIPE_HOOK: Stripe price ID for annual billing',
               existing_nullable=True)
    op.alter_column('plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='FALSE = archived plan, no new subscriptions allowed',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='FALSE = hidden from tenant plan selection (e.g. custom enterprise plans)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='Display order on pricing page. Lower = shown first',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('plans', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_addon_subscriptions', 'subscription_id',
               existing_type=sa.BIGINT(),
               comment='Links addon to base subscription for billing cycle alignment',
               existing_nullable=True)
    op.alter_column('tenant_addon_subscriptions', 'quantity',
               existing_type=sa.INTEGER(),
               comment='Units purchased. effective_grant = grants_per_unit * quantity',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tenant_addon_subscriptions', 'stripe_subscription_item_id',
               existing_type=sa.VARCHAR(length=255),
               comment='STRIPE_HOOK: Stripe subscription item ID for this addon',
               existing_nullable=True)
    op.alter_column('tenant_addon_subscriptions', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenant_addon_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_addon_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_subscriptions', 'status',
               existing_type=postgresql.ENUM('trialing', 'active', 'past_due', 'cancelled', 'paused', name='subscription_status'),
               comment='trialing/active=ok | past_due=read-only | cancelled/paused=block all writes',
               existing_nullable=False,
               existing_server_default=sa.text("'trialing'::subscription_status"))
    op.alter_column('tenant_subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               comment='AUD or USD — determines which price column was used',
               existing_nullable=False,
               existing_server_default=sa.text("'AUD'::character varying"))
    op.alter_column('tenant_subscriptions', 'current_period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Start of current billing period',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='End of current billing period. Reset monthly by Celery task.',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When trial expires. NULL = not in trial.',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When subscription was cancelled.',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               comment='TRUE = cancel at end of current period, not immediately',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tenant_subscriptions', 'notes',
               existing_type=sa.TEXT(),
               comment="Admin payment notes. e.g. 'Paid AUD 300 via bank transfer on 2026-04-09. Ref: INV-001'",
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=255),
               comment='STRIPE_HOOK: Stripe subscription ID',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'stripe_customer_id',
               existing_type=sa.VARCHAR(length=255),
               comment='STRIPE_HOOK: Stripe customer ID',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenant_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_users', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenants', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = active record. Non-NULL = soft-deleted. Always set to UTC.',
               existing_nullable=True)
    op.drop_index('ix_tenants_public_id', table_name='tenants')
    op.create_index(op.f('ix_tenants_public_id'), 'tenants', ['public_id'], unique=True)
    op.alter_column('usage_records', 'metric',
               existing_type=postgresql.ENUM('conversations', 'messages', 'tokens_used', 'pages_crawled', 'documents_uploaded', 'active_users', name='usage_metric'),
               comment='conversations | messages | tokens_used | pages_crawled | documents_uploaded | active_users',
               existing_nullable=False)
    op.alter_column('usage_records', 'quantity',
               existing_type=sa.BIGINT(),
               comment='Cumulative count for this metric in this billing period',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'period_month',
               existing_type=sa.VARCHAR(length=7),
               comment="Billing period in YYYY-MM format e.g. '2026-04'",
               existing_nullable=False)
    op.alter_column('usage_records', 'warned_80',
               existing_type=sa.BOOLEAN(),
               comment='TRUE after 80% warning notification sent this period',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('usage_records', 'warned_90',
               existing_type=sa.BOOLEAN(),
               comment='TRUE after 90% warning notification sent this period',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('usage_records', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last time this record was updated',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True for internal Veloce team members who can access the superadmin panel.'))
    op.alter_column('users', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = active record. Non-NULL = soft-deleted. Always set to UTC.',
               existing_nullable=True)
    op.alter_column('widget_themes', 'public_id',
               existing_type=sa.VARCHAR(),
               comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('widget_themes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('widget_themes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widget_themes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('widget_themes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('widget_themes', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='NULL = active record. Non-NULL = soft-deleted. Always set to UTC.',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('users', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.drop_column('users', 'is_superadmin')
    op.alter_column('usage_records', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last time this record was updated',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('usage_records', 'warned_90',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE after 90% warning notification sent this period',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('usage_records', 'warned_80',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE after 80% warning notification sent this period',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('usage_records', 'period_month',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment="Billing period in YYYY-MM format e.g. '2026-04'",
               existing_nullable=False)
    op.alter_column('usage_records', 'quantity',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Cumulative count for this metric in this billing period',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_records', 'metric',
               existing_type=postgresql.ENUM('conversations', 'messages', 'tokens_used', 'pages_crawled', 'documents_uploaded', 'active_users', name='usage_metric'),
               comment=None,
               existing_comment='conversations | messages | tokens_used | pages_crawled | documents_uploaded | active_users',
               existing_nullable=False)
    op.drop_index(op.f('ix_tenants_public_id'), table_name='tenants')
    op.create_index('ix_tenants_public_id', 'tenants', ['public_id'], unique=False)
    op.alter_column('tenants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='NULL = active record. Non-NULL = soft-deleted. Always set to UTC.',
               existing_nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenants', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenant_users', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenant_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_subscriptions', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenant_subscriptions', 'stripe_customer_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='STRIPE_HOOK: Stripe customer ID',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='STRIPE_HOOK: Stripe subscription ID',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Admin payment notes. e.g. 'Paid AUD 300 via bank transfer on 2026-04-09. Ref: INV-001'",
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE = cancel at end of current period, not immediately',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tenant_subscriptions', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When subscription was cancelled.',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When trial expires. NULL = not in trial.',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='End of current billing period. Reset monthly by Celery task.',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'current_period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Start of current billing period',
               existing_nullable=True)
    op.alter_column('tenant_subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='AUD or USD — determines which price column was used',
               existing_nullable=False,
               existing_server_default=sa.text("'AUD'::character varying"))
    op.alter_column('tenant_subscriptions', 'status',
               existing_type=postgresql.ENUM('trialing', 'active', 'past_due', 'cancelled', 'paused', name='subscription_status'),
               comment=None,
               existing_comment='trialing/active=ok | past_due=read-only | cancelled/paused=block all writes',
               existing_nullable=False,
               existing_server_default=sa.text("'trialing'::subscription_status"))
    op.alter_column('tenant_addon_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_addon_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('tenant_addon_subscriptions', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('tenant_addon_subscriptions', 'stripe_subscription_item_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='STRIPE_HOOK: Stripe subscription item ID for this addon',
               existing_nullable=True)
    op.alter_column('tenant_addon_subscriptions', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Units purchased. effective_grant = grants_per_unit * quantity',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tenant_addon_subscriptions', 'subscription_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Links addon to base subscription for billing cycle alignment',
               existing_nullable=True)
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('plans', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('plans', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Display order on pricing page. Lower = shown first',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('plans', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='FALSE = hidden from tenant plan selection (e.g. custom enterprise plans)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='FALSE = archived plan, no new subscriptions allowed',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'stripe_annual_price_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='STRIPE_HOOK: Stripe price ID for annual billing',
               existing_nullable=True)
    op.alter_column('plans', 'stripe_monthly_price_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='STRIPE_HOOK: Stripe price ID for monthly billing',
               existing_nullable=True)
    op.alter_column('plans', 'limits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Entitlement caps. Keys: max_users, max_chatbots, max_conversations_per_month, max_tokens_per_month, max_tokens_per_conversation, max_documents, max_pages_crawled, max_listings, max_storage_mb. Update via API — no migration needed.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('plans', 'price_usd_cents',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='USD price in cents. 0 = AUD only plan',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('plans', 'price_aud_cents',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='AUD price in cents. e.g. 30000 = AUD 300.00',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('plans', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='URL-safe unique key e.g. project-developments-monthly',
               existing_nullable=False)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name e.g. Project Developments, Single Office Businesses',
               existing_nullable=False)
    op.alter_column('otp_verifications', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('listings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='NULL = active record. Non-NULL = soft-deleted. Always set to UTC.',
               existing_nullable=True)
    op.alter_column('listings', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('knowledge_sources', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('documents', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('crawl_jobs', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('chatbot_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('chatbot_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('chatbot_configs', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('addons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp auto-updated by ORM on every flush.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('addons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp set on INSERT. Never modified after creation.',
               existing_nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'UTC'::text)"))
    op.alter_column('addons', 'public_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.',
               existing_nullable=False)
    op.alter_column('addons', 'stripe_price_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='STRIPE_HOOK: Stripe price ID for this addon',
               existing_nullable=True)
    op.alter_column('addons', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='e.g. { "grants_per_unit": { "max_users": 1 } }',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('addons', 'price_usd_cents',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Per unit per billing interval in USD cents',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('addons', 'price_aud_cents',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Per unit per billing interval in AUD cents',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('addons', 'type',
               existing_type=postgresql.ENUM('extra_users', 'extra_conversations', 'extra_storage', 'premium_widget', name='addon_type'),
               comment=None,
               existing_comment='Addon category — drives which limit key is incremented',
               existing_nullable=False)
    op.alter_column('addons', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='URL-safe unique key e.g. extra-users',
               existing_nullable=False)
    op.alter_column('addons', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name e.g. Extra User Seat',
               existing_nullable=False)
    # ### end Alembic commands ###
