"""make email hash in user nullable

Revision ID: 32c1c48310fe
Revises: d3f8c081ca48
Create Date: 2026-03-31 14:39:32.372782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c1c48310fe'
down_revision: Union[str, None] = 'd3f8c081ca48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='SHA-256(lower(email)). Used to match returning chatbot visitors to a registered user without exposing raw email. Never recalculate from ORM — set explicitly in the service layer before insert.')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='SHA-256(lower(email)). Used to match returning chatbot visitors to a registered user without exposing raw email. Never recalculate from ORM — set explicitly in the service layer before insert.')
    # ### end Alembic commands ###
