"""added tenant and user_tenant table

Revision ID: 3a72ff1a1c70
Revises: 9684313b03d0
Create Date: 2026-04-02 15:35:47.599495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a72ff1a1c70'
down_revision: Union[str, None] = '9684313b03d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Company / agency display name.'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-safe identifier, e.g. 'acme-realty'. Used in routing and subdomain resolution. Immutable after creation."),
    sa.Column('industry', sa.String(length=100), server_default=sa.text("'real_estate'"), nullable=False, comment='Industry vertical. Used for analytics and future vertical-specific features.'),
    sa.Column('status', sa.Enum('pending_plan', 'trial', 'active', 'suspended', 'cancelled', name='tenant_status'), server_default=sa.text("'pending_plan'"), nullable=False, comment='pending_plan=paywall gate | trial=free trial | active=paying | suspended=blocked | cancelled=churned. Single UPDATE here controls access — middleware Gate 1 reads this.'),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment="When the trial period expires. Background job transitions status → 'active' or 'suspended' at this time."),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Whole-unit config: timezone, logo_url, support_email, etc. Always read as a complete blob — never filter or sort inside. Do NOT store secrets here; use a secrets manager.'),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tenants_public_id'), 'tenants', ['public_id'], unique=True)
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.create_index('ix_tenants_status', 'tenants', ['status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('tenant_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='The tenant (company) this membership belongs to.'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='The user being granted access to this tenant.'),
    sa.Column('role', sa.Enum('owner', 'admin', 'agent', 'viewer', name='tenant_role'), server_default=sa.text("'admin'"), nullable=False, comment='owner=1 per tenant (primary owner) | admin=full access | agent=limited write | viewer=read-only.'),
    sa.Column('is_primary_owner', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='Exactly 1 TRUE per tenant. Set when the first user registers their company. Never set via the invite flow.'),
    sa.Column('invited_by', sa.BigInteger(), nullable=True, comment="NULL for the owner who self-registered. Populated with the inviter's user.id for all invited members."),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the invited user accepts the invite and completes signup. NULL means the invite is still pending.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='When the invite was created (or the owner self-registered).'),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_users_tenant_user')
    )
    op.create_index(op.f('ix_tenant_users_public_id'), 'tenant_users', ['public_id'], unique=True)
    op.create_index('ix_tenant_users_role', 'tenant_users', ['tenant_id', 'role'], unique=False)
    op.create_index('ix_tenant_users_tenant', 'tenant_users', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_users_user', 'tenant_users', ['user_id'], unique=False)
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=True)
    op.drop_index('ix_tenant_users_user', table_name='tenant_users')
    op.drop_index('ix_tenant_users_tenant', table_name='tenant_users')
    op.drop_index('ix_tenant_users_role', table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_public_id'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index('ix_tenants_status', table_name='tenants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.drop_index(op.f('ix_tenants_public_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_deleted_at'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
