"""update conversations and messages tables

Revision ID: 4b01d10951cc
Revises: 20b3651eeb1b
Create Date: 2026-02-18 11:51:44.934272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b01d10951cc'
down_revision: Union[str, None] = '20b3651eeb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'Conversation_uuid')
    op.drop_column('messages', 'messages_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('messages_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('Conversation_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
