"""create conversations and messages tables

Revision ID: 5f201be1d81d
Revises: 
Create Date: 2026-02-17 16:11:51.037766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f201be1d81d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('identity_hash', sa.String(), nullable=True),
    sa.Column('visitor_ip_hash', sa.String(), nullable=True),
    sa.Column('visitor_ua', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'closed', 'summarized', 'emailed', 'archived', name='conversationstatus'), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('lead_name', sa.String(), nullable=True),
    sa.Column('lead_email', sa.String(), nullable=True),
    sa.Column('lead_phone', sa.String(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('running_summary', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('archive_url', sa.String(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('ix_conversations_is_lead', 'conversations', ['is_lead'], unique=False)
    op.create_index('ix_conversations_last_activity', 'conversations', ['last_activity_at'], unique=False)
    op.create_index('ix_conversations_session_token', 'conversations', ['session_token'], unique=False)
    op.create_index('ix_conversations_tenant_created', 'conversations', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_conversations_tenant_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conversation_model', 'messages', ['conversation_id', 'model_used'], unique=False)
    op.create_index('ix_messages_conversation_role', 'messages', ['conversation_id', 'role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_role', table_name='messages')
    op.drop_index('ix_messages_conversation_model', table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_tenant_status', table_name='conversations')
    op.drop_index('ix_conversations_tenant_created', table_name='conversations')
    op.drop_index('ix_conversations_session_token', table_name='conversations')
    op.drop_index('ix_conversations_last_activity', table_name='conversations')
    op.drop_index('ix_conversations_is_lead', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
