"""add_billing_tables

Revision ID: 8a3a4141ea8b
Revises: a1b2c3d4e5f6
Create Date: 2026-04-09 13:12:06.661568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a3a4141ea8b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_users', 'status',
               existing_type=postgresql.ENUM('invited', 'active', 'suspended', 'deactivated', name='tenant_user_status'),
               comment='invited=pending | active=joined | suspended=blocked this tenant only | deactivated=removed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::tenant_user_status"))
    op.drop_index('ix_tenants_public_id', table_name='tenants')
    op.create_index(op.f('ix_tenants_public_id'), 'tenants', ['public_id'], unique=True)
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    op.drop_index(op.f('ix_tenants_public_id'), table_name='tenants')
    op.create_index('ix_tenants_public_id', 'tenants', ['public_id'], unique=False)
    op.alter_column('tenant_users', 'status',
               existing_type=postgresql.ENUM('invited', 'active', 'suspended', 'deactivated', name='tenant_user_status'),
               comment=None,
               existing_comment='invited=pending | active=joined | suspended=blocked this tenant only | deactivated=removed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::tenant_user_status"))
    # ### end Alembic commands ###
