"""added conversations insights table

Revision ID: 91a30dec8e6f
Revises: a60089c38a85
Create Date: 2026-03-02 08:42:48.867279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a30dec8e6f'
down_revision: Union[str, None] = 'a60089c38a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('lead_tier', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('budget_currency', sa.String(), nullable=True),
    sa.Column('suburbs_mentioned', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cities_mentioned', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('property_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bedrooms_wanted', sa.Integer(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('topics_mentioned', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_insights', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index('ix_insights_conversation_id', 'conversation_insights', ['conversation_id'], unique=False)
    op.create_index('ix_insights_tenant_budget', 'conversation_insights', ['tenant_id', 'budget_min', 'budget_max'], unique=False)
    op.create_index('ix_insights_tenant_id', 'conversation_insights', ['tenant_id'], unique=False)
    op.create_index('ix_insights_tenant_intent', 'conversation_insights', ['tenant_id', 'intent'], unique=False)
    op.create_index('ix_insights_tenant_lead_tier', 'conversation_insights', ['tenant_id', 'lead_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insights_tenant_lead_tier', table_name='conversation_insights')
    op.drop_index('ix_insights_tenant_intent', table_name='conversation_insights')
    op.drop_index('ix_insights_tenant_id', table_name='conversation_insights')
    op.drop_index('ix_insights_tenant_budget', table_name='conversation_insights')
    op.drop_index('ix_insights_conversation_id', table_name='conversation_insights')
    op.drop_table('conversation_insights')
    # ### end Alembic commands ###
