"""added tenant and user_tenant table

Revision ID: 9684313b03d0
Revises: a5fd79d56624
Create Date: 2026-04-02 15:29:54.462823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9684313b03d0'
down_revision: Union[str, None] = 'a5fd79d56624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
