"""make code nullable in otp

Revision ID: a5fd79d56624
Revises: 32c1c48310fe
Create Date: 2026-04-01 18:30:39.285445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fd79d56624'
down_revision: Union[str, None] = '32c1c48310fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'code_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='SHA-256 of the raw 6-digit code. Raw code is emailed; only the hash is persisted.')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'code_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='SHA-256 of the raw 6-digit code. Raw code is emailed; only the hash is persisted.')
    # ### end Alembic commands ###
