"""new migration

Revision ID: a60089c38a85
Revises: 
Create Date: 2026-02-23 22:37:00.572277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60089c38a85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Internal surrogate PK. Never exposed via API.'),
    sa.Column('public_id', sa.String(), nullable=False, comment='External identifier (uuid7). Exposed in all API responses.'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='Tenant scoping key for multi-tenancy.'),
    sa.Column('session_token', sa.String(), nullable=False, comment='Anonymous session token for widget-based chats.'),
    sa.Column('identity_hash', sa.String(), nullable=True, comment='Optional hashed identity for returning visitor recognition.'),
    sa.Column('visitor_ip_hash', sa.String(), nullable=True),
    sa.Column('visitor_ua', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'closed', 'summarized', 'emailed', 'archived', name='conversationstatus'), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('lead_name', sa.String(), nullable=True),
    sa.Column('lead_email', sa.String(), nullable=True),
    sa.Column('lead_phone', sa.String(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('running_summary', sa.Text(), nullable=True, comment='Rolling summary updated as the conversation grows (context compression).'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Final summary generated when the conversation is closed.'),
    sa.Column('archive_url', sa.String(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False, comment='Updated on every message. Used for idle-timeout detection.'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('ix_conversations_is_lead', 'conversations', ['is_lead'], unique=False)
    op.create_index('ix_conversations_last_activity', 'conversations', ['last_activity_at'], unique=False)
    op.create_index('ix_conversations_public_id', 'conversations', ['public_id'], unique=False)
    op.create_index('ix_conversations_session_token', 'conversations', ['session_token'], unique=False)
    op.create_index('ix_conversations_tenant_cursor', 'conversations', ['tenant_id', 'created_at', 'public_id'], unique=False)
    op.create_index('ix_conversations_tenant_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Internal surrogate PK. Never exposed via API.'),
    sa.Column('public_id', sa.String(), nullable=False, comment='External identifier (uuid7). Returned in API responses.'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='FK to conversations.id (internal PK). Cascades on delete.'),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Token count for this message (input + output for assistant turns).'),
    sa.Column('model_used', sa.String(), nullable=True, comment="LLM model identifier, e.g. 'gpt-4o'. Null for user messages."),
    sa.Column('response_ms', sa.Integer(), nullable=True, comment='LLM response latency in milliseconds. Null for user messages.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conv_role', 'messages', ['conversation_id', 'role'], unique=False)
    op.create_index('ix_messages_public_id', 'messages', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_public_id', table_name='messages')
    op.drop_index('ix_messages_conv_role', table_name='messages')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_tenant_status', table_name='conversations')
    op.drop_index('ix_conversations_tenant_cursor', table_name='conversations')
    op.drop_index('ix_conversations_session_token', table_name='conversations')
    op.drop_index('ix_conversations_public_id', table_name='conversations')
    op.drop_index('ix_conversations_last_activity', table_name='conversations')
    op.drop_index('ix_conversations_is_lead', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
