"""add_tenant_invites_table

Revision ID: ac198940e2dd
Revises: 4493d97e87be
Create Date: 2026-04-10 11:55:21.395948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac198940e2dd'
down_revision: Union[str, None] = '4493d97e87be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_invites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('invitee_user_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'agent', 'viewer', name='tenant_role'), nullable=False),
    sa.Column('otp_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='When this invite email was dispatched. Used for 72h resend restriction.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the invitee accepts. NULL = pending.'),
    sa.Column('public_id', sa.String(), nullable=False, comment='External identifier (uuid7). Time-sortable and non-predictable. Only this ID is exposed in API responses — never the integer PK.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'UTC')"), nullable=False, comment='UTC timestamp set on INSERT. Never modified after creation.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(NOW() AT TIME ZONE 'UTC')"), nullable=False, comment='UTC timestamp auto-updated by ORM on every flush.'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['otp_id'], ['otp_verifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_invites_otp_id', 'tenant_invites', ['otp_id'], unique=False)
    op.create_index(op.f('ix_tenant_invites_public_id'), 'tenant_invites', ['public_id'], unique=True)
    op.create_index('ix_tenant_invites_tenant_invitee', 'tenant_invites', ['tenant_id', 'invitee_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenant_invites_tenant_invitee', table_name='tenant_invites')
    op.drop_index(op.f('ix_tenant_invites_public_id'), table_name='tenant_invites')
    op.drop_index('ix_tenant_invites_otp_id', table_name='tenant_invites')
    op.drop_table('tenant_invites')
    # ### end Alembic commands ###
