"""update conversations and messages tables

Revision ID: af76ac4b52ee
Revises: 5f201be1d81d
Create Date: 2026-02-17 22:58:27.875807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af76ac4b52ee'
down_revision: Union[str, None] = '5f201be1d81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('Conversation_uuid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'Conversation_uuid')
    # ### end Alembic commands ###
