"""added index on identity hash in conversation

Revision ID: d3f8c081ca48
Revises: fb72c892c2ee
Create Date: 2026-03-31 12:45:04.366579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f8c081ca48'
down_revision: Union[str, None] = 'fb72c892c2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conversation_identity_hash', 'conversations', ['identity_hash'], unique=False)
    op.drop_index('ix_users_public_id', table_name='users')
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    op.drop_index('ix_conversation_identity_hash', table_name='conversations')
    # ### end Alembic commands ###
