"""added user and otp table

Revision ID: fb72c892c2ee
Revises: 613e660be068
Create Date: 2026-03-31 12:14:23.400978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb72c892c2ee'
down_revision: Union[str, None] = '613e660be068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Globally unique. Lowercased before insert.'),
    sa.Column('email_hash', sa.String(length=64), nullable=False, comment='SHA-256(lower(email)). Used to match returning chatbot visitors to a registered user without exposing raw email. Never recalculate from ORM — set explicitly in the service layer before insert.'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='NULL for OAuth-only or magic-link-only accounts.'),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Absolute URL to avatar image in S3/CDN.'),
    sa.Column('status', sa.Enum('invited', 'active', 'inactive', 'suspended', name='user_status'), server_default=sa.text("'invited'"), nullable=False, comment='invited=email not verified | active=verified | inactive=deactivated | suspended=locked'),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True, comment='Populated when the user successfully verifies their email via OTP or magic link. NULL means unverified.'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on every successful authentication.'),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_users_email_hash', 'users', ['email_hash'], unique=False)
    op.create_index('ix_users_public_id', 'users', ['public_id'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('otp_verifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='The user this OTP was issued for.'),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', 'login_otp', name='otp_purpose'), nullable=False, comment='email_verification | password_reset | login_otp. Drives email template and expiry duration.'),
    sa.Column('code_hash', sa.String(length=64), nullable=False, comment='SHA-256 of the raw 6-digit code. Raw code is emailed; only the hash is persisted.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Hard expiry. Reject verification after this timestamp.'),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True, comment='Set atomically on successful verification. NULL = not yet used.'),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Incremented on every failed attempt. Reject when >= max_attempts.'),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False, comment='Maximum allowed wrong guesses before this OTP is invalidated.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IPv4 or IPv6 address of the request that triggered OTP issue.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_expires', 'otp_verifications', ['expires_at'], unique=False)
    op.create_index('ix_otp_user_purpose_active', 'otp_verifications', ['user_id', 'purpose'], unique=False, postgresql_where=sa.text('consumed_at IS NULL'))
    op.create_index(op.f('ix_otp_verifications_public_id'), 'otp_verifications', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verifications_public_id'), table_name='otp_verifications')
    op.drop_index('ix_otp_user_purpose_active', table_name='otp_verifications', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_index('ix_otp_expires', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index('ix_users_status', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_users_public_id', table_name='users')
    op.drop_index('ix_users_email_hash', table_name='users')
    op.drop_index('ix_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
