"""chatbot_iframe_token_string36

Revision ID: fd90108b12bc
Revises: 1f71dab81632
Create Date: 2026-04-10 01:08:20.170444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd90108b12bc'
down_revision: Union[str, None] = '1f71dab81632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_configs', 'iframe_token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               comment='Public embed key (uuid7). Never expose tenant_id in widget URL.',
               existing_comment='Public embed key. Never expose tenant_id in widget URL.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_configs', 'iframe_token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               comment='Public embed key. Never expose tenant_id in widget URL.',
               existing_comment='Public embed key (uuid7). Never expose tenant_id in widget URL.',
               existing_nullable=False)
    # ### end Alembic commands ###
